defaults:
  - physicsnemo_default
  - arch:
    - fully_connected
  - optimizer: adamw
  - loss: sum
  - scheduler: exponential_lr
  - _self_


scheduler:
  gamma: 1

amp:
  enabled: false


training:
   rec_monitor_freq: 200
   rec_constraint_freq: 200
   rec_inference_freq: 200
   max_steps : 10000
   ntk:
     use_ntk: False
     save_name: null
     run_freq: 5

batch_size:
  boundary: 1500
  initial: 1500
  inter: 10000

optimizer:
   lr: 1e-4

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/Adam

cuda_graphs: true

graph:
  func_arch: true

custom:
  quasirandom: true